#
# Network
#

# PUT network info (should fail)
PUT http://localhost:3001/api/net

# Options network
OPTIONS http://localhost:3001/api/net

# Get network info
GET http://localhost:3001/api/net

# Create a new network
POST http://localhost:3001/api/net
Content-Type: application/json
Accept: application/json

{
  "name": "test-a",
  "topology": [10, 16, 8, 8, 10],
  "thread_count": 1
}

# Create a new network
POST http://localhost:3001/api/net
Content-Type: application/json
Accept: application/json

{
  "name": "test-a",
  "topology": [2, 8, 4, 1],
  "thread_count": 1
}

# Bad call to create a network
POST http://localhost:3001/api/net
Content-Type: application/json
Accept: application/json

{
  "bogus": hello world
}


# Delete the network
DELETE http://localhost:3001/api/net

#
# List neurons and connections

# Get network's neurons
GET http://localhost:3001/api/neurons?page-size=100000

# Get neuron
GET http://localhost:3001/api/neurons?name=none

# Get network's connections
GET http://localhost:3001/api/connections?page-size=5

# Get network's connections
GET http://localhost:3001/api/connections?page-size=30

# Get specific network connection
GET http://localhost:3001/api/connections?id=-1

#
# Network training
#

# OPTIONS /api/train
OPTIONS http://localhost:3001/api/train

# PUT /api/train (should fail)
PUT http://localhost:3001/api/train

# Get network training status
GET http://localhost:3001/api/train

# Train network
POST http://localhost:3001/api/train
Content-Type: application/json

{
  "target_error": 0.05,
  "max_iterations": 5000,
  "update_frequency": 0.5
}

# Delete weights
DELETE http://localhost:3001/api/train

# Get Training set
GET http://localhost:3001/api/training-set

# Put Training set
PUT http://localhost:3001/api/training-set
Content-Type: application/json
Accept: application/json

{"frames":[{"id":"1","in":[0.01,0],"out":[0]}]}

# Post training set
POST http://localhost:3001/api/training-set
Content-type: application/json

{
  frames: [
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  ]
}

# Post training set
POST http://localhost:3001/api/training-set
Content-type: application/json

{
  "frames": [
    {"id": "1", "in": [0, 0], "out": [0]},
    {"id": "2", "in": [0, 1], "out": [1]},
    {"id": "3", "in": [1, 0], "out": [1]},
    {"id": "4", "in": [1, 1], "out": [0]}
  ]
}

# Post training set
PUT http://localhost:3001/api/training-set
Content-type: application/json

{
  "frames": [
    {"id": "1", "in": [1, 1], "out": [0.00]}
  ]
}

# Delete training set
DELETE http://localhost:3001/api/training-set
