(defpackage :bianet
  (:use :cl :dc-dlist :dc-eclectic :sb-concurrency :sb-thread :cl-ppcre)
  (:export
   ;; neuron methods
   adjust-weight
   adjust-weights
   biased-derivative
   biased-transfer
   compute-new-weight
   connect
   disconnect
   evaluate-error-messages
   evaluate-input-messages
   excite
   excite-internal
   fire-error
   fire-output
   initialize-instance
   isolate
   list-incoming
   list-incoming-weights
   list-outgoing
   logistic
   logistic-derivative
   modulate
   modulate-internal
   name
   next-cx-id
   next-cx-id-peek
   next-neuron-id
   next-neuron-id-peek
   next-weight
   process
   relu
   relu-derivative
   reset-ids
   reset-random-state
   reset-state
   t-cx
   t-neuron
   transfer
   transfer-error
   wait-for-backprop-p
   wait-for-output-p

   ;; neuron attributes
   biased
   bp-count
   delta
   e-mailbox
   err
   err-in
   err-in-last
   err-last
   excitation-count
   excited
   ff-count
   fire-count
   i-mailbox
   id
   incoming
   input
   input-last
   layer
   learning-rate
   modulated
   modulation-count
   momentum
   on-backprop
   on-output
   outgoing
   output
   output-last
   process-count
   running
   source
   target
   transfer-count
   transfer-derivative
   transfer-function
   transfer-key
   update-count
   weight
   weight-last

   ;; network methods
   **inputs-ready-count**
   **outputs-ready-count**
   compute-cx-count
   compute-weights-random
   compute-weights-sinusoidal
   connect-layers
   create-simple-network
   simple-network-layers
   ))
